---
- name: Attempt to retreive the NFD Operator RoleBindings
  command: oc get rolebinding '{{ rolebinding_name }}' -n '{{ nfd_operator_namespace }}' -oname | grep 'error'
  register: nfd_operator_rolebindings_do_not_exist
  failed_when: false
  with_items:
    - '{{ nfd_operator_leader_election_rolebinding }}'
    - '{{ nfd_operator_worker_rolebinding }}'
  loop_control:
    loop_var: rolebinding_name

- name: If any of the NFD Operator RoleBindings do not exist, then we cannot continue
  fail: msg="All NFD Operator RoleBindings must be initialized before running this role"
  when: rolebinding_status.stdout_lines == ''
  with_items: "{{ nfd_operator_rolebindings_do_not_exist.results }}"
  loop_control:
    loop_var: rolebinding_status
    label: "{{ rolebinding_status.rolebinding_name }}"
