---
- name: Attempt to retreive the NFD SecurityContextConstraints, {{ nfd_operator_scc }}
  command: oc get '{{ nfd_operator_scc }}' -n '{{ nfd_operator_namespace }}' -oname | grep 'error'
  register: nfd_operator_scc_does_not_exist
  failed_when: false

- name: If the NFD Operator SecurityContextConstraints does not exist, then we cannot continue
  fail: msg="The '{{ nfd_operator_scc }}' SecurityContextConstraints is not initially available"
  when: nfd_operator_scc_does_not_exist.stdout_lines == ''
