---
- name: Attempt to retreive the NFD Service, service/{{ nfd_operator_service }}
  command: oc get '{{ nfd_operator_service }}' -n '{{ nfd_operator_namespace }}' -oname | grep 'error'
  register: nfd_operator_svc_does_not_exist
  failed_when: false

- name: If the NFD Operator Service does not exist, then we cannot continue
  fail: msg="The '{{ nfd_operator_service }}' Service is not initially available"
  when: nfd_operator_svc_does_not_exist.stdout_lines == ''
