---
- name: Attempt to retreive the NFD Operator ServiceAccounts
  command: oc get sa '{{ serviceaccount_name }}' -n '{{ nfd_operator_namespace }}' -oname | grep 'error'
  register: nfd_operator_sas_do_not_exist
  failed_when: false
  with_items:
    - '{{ nfd_operator_serviceaccount_worker }}'
    - '{{ nfd_operator_serviceaccount_master }}'
    - '{{ nfd_operator_serviceaccount_operator }}'
  loop_control:
    loop_var: serviceaccount_name

- name: If any of the NFD Operator ServiceAccounts do not exist, then we cannot continue
  fail: msg="All NFD Operator ServiceAccounts must be initialized before running this role"
  when: serviceaccount_status.stdout_lines == ''
  with_items: "{{ nfd_operator_sas_do_not_exist.results }}"
  loop_control:
    loop_var: serviceaccount_status
    label: "{{ serviceaccount_status.serviceaccount_name }}"
